name: 'Email Notification Workflow'

on: workflow_dispatch

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Convert Notebook"
        run: |
          pip install jupyter
          pip install -r requirements.txt
          jupyter nbconvert --to html --execute analysis.ipynb --no-input
      - name: 'Send Mail'
        uses: dawidd6/action-send-mail@v18
        with:
          server_address: smtp.gmail.com
          username: sammyseal22@gmail.com 
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions Test
          to: smartinez2@clevelandohio.gov
          html_body: file://analysis.ipynb
